#index:
#    path: /
#    controller: App\Controller\DefaultController::index

new:
  path: /currency
  controller: App\Controller\CurrencyController:new

createExchange:
  path: /currency/v1/create
  controller: App\Controller\CurrencyController:createExchange
  methods: [POST]
